//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por estructuraDatos-1.rc
//
#define MODIFICAR_ESPECIALIDADES        9
#define IDD_DIALOG1                     101
#define IDD_DIALOG2                     103
#define IDC_CURSOR1                     105
#define REG_ESPECIALIDADES              106
#define REG_PACIENTES                   108
#define CONSULTA_MEDICO_MES_VENTANA     110
#define BUSCAR_ESPECIALIDAD             112
#define REGISTRAR_MEDICOS               116
#define MODIFICAR_MEDICOS               118
#define BUSCAR_MEDICOS                  118
#define MODIFICAR_MEDICO                120
#define CAMBIAR_NOMBRE_MEDICO           122
#define REGISTRAR_CITAS                 124
#define BUSCAR_PACIENTES                126
#define AGENDAR_CITA                    128
#define CONSULTA_SEMANA_ESPECIALIDAD    130
#define CONSULTA_ESPECIALIDAD_MES       132
#define EDIT_USUARIO                    1001
#define EDIT_CONTRASENIA                1002
#define BTN_REGISTRARSE                 1003
#define EDIT_REGNOMBRE                  1004
#define EDIT_REGUSUARIO                 1005
#define EDIT_REGCONTRASENIA             1006
#define EDIT_REGCONTRASENIACONF         1007
#define TXT_ESPECIALIDAD                1009
#define TXT_DESCRIPCION                 1010
#define TXT_PACIENTE_NOMBRE             1011
#define RD_GENERO_HOMBRE                1012
#define RD_GENERO_MUJER                 1014
#define TXT_PACIENTE_TELEFONO           1015
#define CB_PACIENTE_MEDICO              1017
#define CB_PACIENTES_REFERENCIA         1019
#define CB_FECHA_DIA                    1020
#define CB_FECHA_MES                    1021
#define CB_FECHA_ANIO                   1022
#define CB_PACIENTE_EDAD                1024
#define BTN_ESPECIALIDAD_BUSCAR         1025
#define TXT_BUSCAR_ESPECIALIDAD         1027
#define LB_BUSCAR_ESPECIALIDADES        1028
#define CK_TODOS_ESPECIALIDADES         1030
#define BTN_BUSCAR_ESPECIALIDADES       1031
#define TXT_ESPECIALIDAD_ENCONTRADA     1032
#define BTN_ELIMINAR_ESPECIALIDAD       1033
#define BTN_MODIFICAR                   1034
#define TXT_DESCRIPCION_ECONTRADA       1035
#define TXT_CEDULA_MEDICO               1038
#define TXT_NOMBRE_MEDICO               1039
#define TXT_APELLIDOP_MEDICO            1040
#define TXT_APELLIDOM_MEDICO            1041
#define CB_HORARIO_INICIO               1042
#define CB_HORARIO_FIN                  1043
#define TXT_NUMERO_MEDICO               1044
#define CB_SELECCION_DIAS               1045
#define LB_DIAS_SELECCIONADOS           1046
#define BTN_SELECT_PHOTO                1048
#define PC_IMAGE                        1050
#define CB_ROOM_MEDIC                   1052
#define CB_ESPECIALIDAD_MEDICO          1053
#define TXT_CEDULA                      1054
#define LB_NOMBRES_MEDICOS              1055
#define CB_SELECT_VIEW                  1058
#define CB_ESPECIALIDAD                 1059
#define BTN_BUSCAR_MEDICO               1060
#define TXT_EDIT_NOMBRE_MEDICO          1062
#define BTN_EDIT_NOMBRE                 1063
#define TXT_EDIT_CEDULA                 1065
#define TXT_EDIT_TELEFONO               1067
#define BTN_EDIT_ESPECIALIDAD_MEDICO    1069
#define CB_EDIT_DIAS                    1071
#define CB_EDIT_HORARIO                 1073
#define LB_DIAS_EDITADOS                1075
#define EDIT_FOTO                       1076
#define BTN_EDIT_FOTO                   1078
#define CB_EDIT_ESPECIALIDAD            1079
#define BTN_BUSCAR_DIAS                 1080
#define CB_EDIT_CUARTO                  1081
#define LB_DIAS_ACTUALES                1084
#define BTN_CAMBIAR_HORARIO             1086
#define TXT_NOMBRE                      1087
#define TXT_M_APELLIDO                  1088
#define TXT_P_APELLIDO                  1089
#define BTN_ELIMINAR_MEDICO             1089
#define IDC_COMBO1                      1092
#define TXT_PACIENTE_APELLIDO           1093
#define TXT_PACIENTE_APELLIDO2          1095
#define LB_PACIENTES                    1096
#define CK_ENABLE_DOCTORES              1098
#define CB_MEDICO                       1099
#define CK_NOMBRE_PACIENTE              1100
#define BTN_EDITAR_PACIENTE             1103
#define TXT_EDIT_TELEFONO_PACIENTES     1104
#define TXT_EDIT_PACIENTE_NOMBRE        1105
#define TXT_EDIT_PACIENTE_APELLIDO1     1107
#define TXT_EDIT_PACIENTE_APELLIDO2     1108
#define TXT_EDAD_PACIENTE               1109
#define ST_GENERO_PACIENTE              1110
#define CB_EDIT_MES_PACIENTE            1112
#define CB_EDIT_ANIO_PASIENTE           1113
#define CB_EDIT_DIA_PACIENTE            1114
#define ST_FECHA_NACIMIENTO_PACIENTE    1115
#define BTN_ELIMINAR_PACIENTE           1116
#define DTP_AGENDA_CITA                 1118
#define CB_ESCOGER_MEDICO               1119
#define CB_ESPECIALIDAD_CITA            1120
#define LB_MEDICOS                      1121
#define LB_HORARIO_AGENDA               1122
#define ST_NOMBRE_MEDICO                1124
#define TXT_SPECIALIDAD_CITA            1125
#define BTN_SELECCIONAR_MEDICO          1126
#define PC_AGENDA_IMAGEN                1127
#define CB_PACIENTE_CITA                1128
#define ST_CEDULA_CITA                  1129
#define LB_DISP_CITA                    1137
#define BTN_AGENDA_DOCTOR               1138
#define CB_HORA_CITA                    1141
#define CB_MES                          1144
#define CB_CONSULTA_MES                 1144
#define CB_CONSULTA_MEDICO              1146
#define ST_CONSULTA_NOMBRE_MEDICO       1147
#define ST_CONSULTA_MEDICO_ESPECIALIDAD 1148
#define CB_MES_CONSULTA                 1150
#define CB_CONSULTA_SEMANA              1152
#define CB_TIPO_REGISTRO                1153
#define CB_REGISTRO_SEMANA              1154
//#define IDC_COMBO2                      1155
#define CB_REGISTRO_ESPECIALIDAD        1155

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1156
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
